//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonsDataWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int Id { get; set; }
        public int DistrictId { get; set; }
        public int CountyId { get; set; }
        public string City1 { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual County County { get; set; }
        public virtual District District { get; set; }
    }
}
