//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonsDataWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime YearOfBirth { get; set; }
        public int ResidenceAddressId { get; set; }
        public int CorrespondenceAddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
    }
}
